language: python
python:
    "3.7"
virtualenv:
    system_site_packages: true

install:
    - pip install --upgrade pip
    - pip install --upgrade -r requirements.txt
script:
    - python setup.py test
